name: ruudforce.com
favicon: null
layout_spectrum: 0.4915530390571803
typography_spectrum: 0.03947204537689686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1755513504613191
  lightness: 0.6006131472531706
  saturation: 0.8345997147262096
  rhythmicContrast: 0.7169001277070493
purpose: []
