name: ruudforce.com
favicon: null
layout_spectrum: 0.38022
typography_spectrum: 0.5164
title: RuudForce.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f8f8'
    - '#c9ccd0'
    - '#12161c'
    - '#9eaeb6'
    - '#617987'
  brandStrength: 0.1755513504613191
  lightness: 0.6006131472531706
  saturation: 0.8345997147262096
  rhythmicContrast: 0.7169001277070493
purpose: []
